//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolotinTour
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelPhoto
    {
        public int Code { get; set; }
        public Nullable<int> CodeHotel { get; set; }
        public byte[] Preview { get; set; }
        public string PhotoLink { get; set; }
    
        public virtual Hotel Hotel { get; set; }
    }
}
