//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolotinTour
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hotel()
        {
            this.HotelPhoto = new HashSet<HotelPhoto>();
            this.HotelReview = new HashSet<HotelReview>();
            this.Service = new HashSet<Service>();
            this.Tour = new HashSet<Tour>();
        }
    
        public int Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> PartnerCode { get; set; }
        public Nullable<int> Stars { get; set; }
        public Nullable<int> CountryCode { get; set; }
        public Nullable<int> CodeHotelPhoto { get; set; }
        public Nullable<int> CodeHotelReview { get; set; }
        public Nullable<int> Place { get; set; }
        public string Adress { get; set; }
        public string Parking { get; set; }
        public string Transfer { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Partner Partner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelPhoto> HotelPhoto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelReview> HotelReview { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service> Service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tour> Tour { get; set; }
    }
}
