//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolotinTour
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerContract
    {
        public int ContractCode { get; set; }
        public Nullable<int> CodePartner { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateExpiration { get; set; }
    
        public virtual Partner Partner { get; set; }
    }
}
