//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolotinTour
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int Code { get; set; }
        public string CodeReservation { get; set; }
        public string FIO { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public Nullable<int> Room { get; set; }
        public Nullable<int> Days { get; set; }
        public Nullable<int> Nights { get; set; }
        public Nullable<decimal> PricePerNight { get; set; }
        public Nullable<decimal> ReservationPrice { get; set; }
        public string HotelName { get; set; }
        public string FoodType { get; set; }
    }
}
