//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolotinTour
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourApplication
    {
        public int Code { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> CodeClient { get; set; }
        public Nullable<int> CodeContractClient { get; set; }
        public Nullable<int> CodePartner { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> ApplicationStatus { get; set; }
        public string Commentary { get; set; }
    
        public virtual ApplicationStatus ApplicationStatus1 { get; set; }
        public virtual Client Client { get; set; }
        public virtual ContractClient ContractClient { get; set; }
        public virtual Partner Partner { get; set; }
    }
}
