//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolotinTour
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourService
    {
        public int Code { get; set; }
        public bool ToControl { get; set; }
    
        public virtual Tour Tour { get; set; }
    }
}
