//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolotinTour
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        public int Code { get; set; }
        public string TourName { get; set; }
        public string TourDescription { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<int> TourType { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> HotelCode { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual TourService TourService { get; set; }
        public virtual TourType TourType1 { get; set; }
    }
}
