//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolotinTour
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoucherApplication
    {
        public int Code { get; set; }
        public Nullable<int> CodeApplication { get; set; }
        public Nullable<System.DateTime> DateApplication { get; set; }
        public Nullable<int> CodeClient { get; set; }
        public Nullable<int> CodeClientContract { get; set; }
        public Nullable<int> CodeService { get; set; }
        public byte[] Voucher { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ContractClient ContractClient { get; set; }
        public virtual Service Service { get; set; }
    }
}
